### ISSUE TITLE
Failed to unlock: The response is not of given type

### ISSUE THREAD

**Issue by zanix** [wdhongtw/vscode-gpg-indicator#30] opened 2022-04-10 02:29 UTC
As of version 0.6.0, when unlocking the key, I get the following error as a VSCode notification.

> Failed to unlock: The response is not of given type

This is what is displayed in the Output panel:

```
Try to unlock current key: <GPG>
Assuan data receive: OK Pleased to meet you, process 13156
Assuan data send: OPTION pinentry-mode loopback
Assuan data receive: OK
Assuan data send: SIGKEY <SIGKEY>
Assuan data receive: OK
Assuan data send: SETHASH --hash=sha1 <sha1>
Assuan data receive: OK
Assuan data send: PKSIGN
Assuan data receive: S INQUIRE_MAXLEN 255
Assuan data receive: INQUIRE PASSPHRASE
Assuan data send: D <passphrase>
Assuan data send: END
Assuan data receive: ERR 67108875 Bad passphrase <GPG Agent>
```

If I revert to 0.5.0 it unlocks without issue.

My passphrase uses special characters like `|#%*`.

**Comment by zanix** [comment] 2022-05-21 15:54
Is there anything I can do to help get more information on this bug?

**Comment by wdhongtw** [comment] 2022-05-29 14:37
The problem is that when sending the passphrase through the socket, the raw data (passphrase must go through %-encoding). Since the `%` character itself should be encoded as well, currently the any passphrase contains `%` will be broken.

A workaround is to replace `%` with `%25` when typing passphrase in the input box. :)

Also, if you would like to submit some PR, I thought there are two places should be fixed in the code base.

- <https://github.com/wdhongtw/vscode-gpg-indicator/blob/master/src/indicator/assuan.ts#L47>
- <https://github.com/wdhongtw/vscode-gpg-indicator/blob/master/src/indicator/assuan.ts#L184>

And sorry for the late response, I'm kinda busy these days. :(

Reference

- <https://www.gnupg.org/documentation/manuals/assuan/Client-requests.html#Client-requests>
- <https://www.gnupg.org/documentation/manuals/assuan/Server-responses.html#Server-responses>

**Comment by zanix** [comment] 2022-05-29 17:37
No problem with the slow response, I understand being busy.
The `%25` workaround does work. If I get some time I'll attempt to fix it and submit a PR.
I just need to figure out how to work on a VSCode extension.

**Closed** 2022-06-03 04:35 UTC
Labels: bug
